"""The adversarial hardening harness: build a detector, attack it, measure the damage,
retrain, prove the recovery.

Guardrail (repeated from README.md and strategies.py because it matters): every attack
here runs entirely against this repo's own locally-loaded model files, scoring
synthetic sandbox rings generated by this repo's own generator. No network calls, no
real accounts, no reusable offense tooling — a parametrized search over synthetic-data
shape, nothing more.

Honesty checkpoint (see docs/ARCHITECTURE.md, panel pushback #1): this validates
robustness to the THREE evasion classes implemented here, searched adaptively within
their parameter ranges. It is not a general adversarial-robustness guarantee, and a
real fraud ring is not obligated to restrict itself to these three strategies. That
limitation is real and is reported alongside the results, not hidden from them.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass

import numpy as np
import pandas as pd

from cerberus.adversarial.attacker import DetectionScore, SearchResult, adaptive_search, score_ring
from cerberus.adversarial.strategies import (
    STRATEGY_APPLIERS,
    STRATEGY_PARAM_BOUNDS,
    generate_baseline_ring,
)
from cerberus.data.synthetic_rings import build_entity_edges
from cerberus.detection.calibration import fit_calibrator
from cerberus.detection.point_risk import fit_classifier
from cerberus.features.pipeline import FEATURE_COLUMNS, build_features

STRATEGIES = ("structuring", "identity_rotation", "slow_ramp")
N_HARDENING_RINGS_PER_STRATEGY = 15


@dataclass
class StrategyReport:
    strategy: str
    baseline: DetectionScore
    evaded_original: DetectionScore
    best_params: dict
    evaded_hardened: DetectionScore | None = None


def run_evasion_search(
    booster,
    calibrator,
    segment_routing: dict,
    global_default_threshold: float,
    rng: np.random.Generator,
    n_restarts: int = 5,
    n_steps: int = 15,
) -> dict[str, SearchResult]:
    """Run the adaptive search for all three strategies against one model+calibrator."""

    def scorer(ring):
        return score_ring(ring, booster, calibrator, segment_routing, global_default_threshold)

    results = {}
    for strategy in STRATEGIES:
        results[strategy] = adaptive_search(
            strategy_name=strategy,
            applier=STRATEGY_APPLIERS[strategy],
            param_bounds=STRATEGY_PARAM_BOUNDS[strategy],
            make_base_ring=lambda: generate_baseline_ring(rng, ring_size=int(rng.integers(4, 10))),
            score_fn=scorer,
            rng=rng,
            n_restarts=n_restarts,
            n_steps=n_steps,
        )
    return results


def generate_hardening_examples(
    strategy_results: dict[str, SearchResult], rng: np.random.Generator, n_per_strategy: int = N_HARDENING_RINGS_PER_STRATEGY
) -> pd.DataFrame:
    """Generate a batch of adversarial examples using each strategy's best-evading
    parameters — the actual attacks the harness found — and featurize them exactly as
    scoring did, ready to be appended to the training set.
    """
    all_features = []
    for strategy, result in strategy_results.items():
        if not result.best_params:
            continue
        applier = STRATEGY_APPLIERS[strategy]
        for _ in range(n_per_strategy):
            base_ring = generate_baseline_ring(rng, ring_size=int(rng.integers(4, 10)))
            attacked = applier(base_ring, rng, **result.best_params)
            if len(attacked.transactions) == 0:
                continue
            entity_edges = build_entity_edges(attacked.transactions)
            features = build_features(attacked.transactions, entity_edges)
            all_features.append(features)

    if not all_features:
        return pd.DataFrame(columns=[*FEATURE_COLUMNS, "label"])
    return pd.concat(all_features, ignore_index=True)


def retrain_hardened_model(train_df: pd.DataFrame, calib_df: pd.DataFrame, adversarial_examples: pd.DataFrame, random_seed: int):
    """Retrain on original training data + the adversarial examples the harness found,
    recalibrate on the SAME original calibration split (untouched, so calibration still
    reflects genuine held-out generalization rather than being fit on the attacks
    it's supposed to be evaluated against).
    """
    augmented_train = pd.concat([train_df[[*FEATURE_COLUMNS, "label"]], adversarial_examples[[*FEATURE_COLUMNS, "label"]]], ignore_index=True)
    X_train, y_train = augmented_train[FEATURE_COLUMNS], augmented_train["label"]
    hardened_model = fit_classifier(X_train, y_train)

    raw_calib = hardened_model.predict_proba(calib_df[FEATURE_COLUMNS])[:, 1]
    calibrator = fit_calibrator(raw_calib, calib_df["label"].to_numpy())
    return hardened_model, calibrator


def score_summary(strategy_results: dict[str, SearchResult]) -> list[StrategyReport]:
    return [
        StrategyReport(
            strategy=name,
            baseline=r.baseline_score,
            evaded_original=r.best_score,
            best_params=r.best_params,
        )
        for name, r in strategy_results.items()
    ]


def report_to_dict(reports: list[StrategyReport]) -> dict:
    return {
        r.strategy: {
            "baseline_detection": asdict(r.baseline),
            "evaded_original_model": asdict(r.evaded_original),
            "evaded_hardened_model": asdict(r.evaded_hardened) if r.evaded_hardened else None,
            "best_evasion_params": r.best_params,
            "recall_decay_original": r.baseline.combined_score - r.evaded_original.combined_score,
            "recall_recovered_after_hardening": (
                r.evaded_hardened.combined_score - r.evaded_original.combined_score
                if r.evaded_hardened
                else None
            ),
        }
        for r in reports
    }
